---
name: 'YAML/JSON/XML Converter Action'
author: Yevhen Fabizhevskyi
description: 'This action takes file that in YAML/JSON/XML format and produces it in output in YAML/JSON/XML format.'
branding:
  icon: copy
  color: green
inputs:
  path:
    description: 'Path to the file'
    required: true
  from:
    description: 'Format of a file. Possible values: json, xml, yaml.'
    required: true
  to:
    description: 'Format of a file as a result. Possible values: json, xml, yaml.'
    required: true
outputs:
  data:
    description: 'Content of a file in a format that is defined in format_to argument.'
    value: ${{ steps.result.outputs.data }}
runs:
  using: 'composite'
  steps:
    # From YAML/JSON
    - name: JSON/YAML to JSON/XML
      id: mikefarah_yq
      uses: mikefarah/yq@v4.28.1
      if: ${{ inputs.from == 'yaml' || inputs.from == 'json' }}
      with:
        cmd: yq -P '${{ inputs.path }}' -o=${{ inputs.to }}
    - name: Save to file
      if: ${{ inputs.from == 'yaml' || inputs.from == 'json' }}
      run: echo '${{ steps.mikefarah_yq.outputs.result }}' > .yaml-json-xml-converter-action
      shell: bash
    # From XML
    - name: Install yq
      if: ${{ inputs.from == 'xml' }}
      run: pip install yq==3.1.0
      shell: bash
    - name: XML to JSON
      if: ${{ inputs.from == 'xml' && inputs.to == 'json' }}
      run: xq . '${{ inputs.path }}' > .yaml-json-xml-converter-action
      shell: bash
    - name: XML to YAML
      if: ${{ inputs.from == 'xml' && inputs.to == 'yaml' }}
      run: xq . '${{ inputs.path }}' | yq -y . > .yaml-json-xml-converter-action
      shell: bash
    - name: Uninstall yq
      if: ${{ inputs.from == 'xml' }}
      run: pip uninstall -y yq
      shell: bash
    # Output
    - name: Save output
      id: result
      run: |
        content=$(cat .yaml-json-xml-converter-action)
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=data::$content"
        rm -f .yaml-json-xml-converter-action
      shell: bash
